version: '3.9'

services:

  postgres:
    image: postgres:13
    container_name: postgres_smartcity
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    networks:
      - smartcity-net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_smartcity
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - ./docker_data/zookeeper:/bitnami
    networks:
      - smartcity-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka_smartcity
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka_smartcity:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    volumes:
      - ./docker_data/kafka:/bitnami/kafka
    networks:
      - smartcity-net

  flink-jobmanager:
    image: flink:1.20.0-scala_2.12
    container_name: flink_jobmanager
    command: jobmanager
    ports:
      - "18081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - FLINK_CLASSPATH=/opt/flink/connectors/*
    volumes:
      - ./docker_data/flink/connectors:/opt/flink/connectors
      - ./docker_data/flink/jobs:/opt/flink/jobs        # JAVA JOBS HERE
      - ./docker_data/flink/checkpoints:/opt/flink/checkpoints
      - ./docker_data/flink/savepoints:/opt/flink/savepoints
      - ./docker_data/flink/jobmanager:/opt/flink/data
    networks:
      - smartcity-net

  flink-taskmanager:
    image: flink:1.20.0-scala_2.12
    container_name: flink_taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - FLINK_CLASSPATH=/opt/flink/connectors/*
    volumes:
      - ./docker_data/flink/connectors:/opt/flink/connectors
      - ./docker_data/flink/jobs:/opt/flink/jobs        # JAVA JOBS
      - ./docker_data/flink/checkpoints:/opt/flink/checkpoints
      - ./docker_data/flink/savepoints:/opt/flink/savepoints
      - ./docker_data/flink/taskmanager:/opt/flink/data
    networks:
      - smartcity-net

networks:
  smartcity-net:
    driver: bridge
