version: '3.9'

services:

  postgres:
    image: postgres:14
    container_name: postgres_smartcity
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    networks:
      - smartcity-net


  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_smartcity
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - ./docker_data/zookeeper:/bitnami
    networks:
      - smartcity-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka_smartcity
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    volumes:
      - ./docker_data/kafka:/bitnami/kafka
    networks:
      - smartcity-net

networks:
  smartcity-net:
    driver: bridge
